"""
this was generated by an AI coding assistant based on NN.py
This is a hardcoded 2 input neuron, 3 hidden layer neurons and one output neuron neural network.
"""

# Set non-interactive backend
import matplotlib
matplotlib.use('Agg')
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation, FFMpegWriter
from mpl_toolkits.mplot3d import Axes3D
import os

# Set random seed for reproducibility
np.random.seed(42)

# Activation functions
def relu(x):
    return np.maximum(0, x)

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Generate 2D linear data (3D: x, y -> z)
# Use a 100x100 grid as requested
x_range = np.linspace(0, 100, 100)
y_range = np.linspace(0, 100, 100)
X1, X2 = np.meshgrid(x_range, y_range)
X_grid = np.column_stack((X1.ravel(), X2.ravel()))
X = X_grid

# Create a linear relation: z = 0.5 * x1 + 0.3 * x2 + 10
# Normalize z to be between 0 and 1 for sigmoid output (using a simple scaling for now)
# Since inputs are up to 100, we need to be careful with the sigmoid range
# Let's normalize X for training and use it for labels
X_norm = X / 100.0
true_weights = np.array([0.5, 0.3])
true_bias = 0.1
z = np.dot(X_norm, true_weights) + true_bias
labels = z.reshape(-1, 1)

# Initialize parameters
# 3 neuron hidden layer according to 2 inputs (3 by 2 matrix)
W1 = np.random.randn(3, 2) * 2.0
b1 = np.random.randn(3) * 2.0

# 1 neuron output layer according to 3 inputs (1 by 3 matrix)
W2 = np.random.randn(3) * 2.0
b2 = np.array([2.0])

learning_rate = 0.2
epochs = 1000
plot_every = 1

losses = []
all_preds = []
epoch_list = []

print(f"Training on {len(X)} samples...")

for i in range(epochs):
    # Vectorized Forward propagation
    # X_norm shape: (10000, 2)
    # W1 shape: (3, 2) -> W1.T shape: (2, 3)
    z1 = np.dot(X_norm, W1.T) + b1  # (10000, 3)
    a1 = relu(z1)  # (10000, 3)
    z2 = np.dot(a1, W2.T) + b2  # (10000, 1)
    pred = sigmoid(z2)  # (10000, 1)

    # Calculate loss
    loss = np.mean((pred - labels)**2)
    losses.append(loss)

    # Backward propagation (MSE)
    # labels shape is (10000, 1), pred shape is (10000, 1)
    # Ensure they are indeed column vectors
    pred = pred.reshape(-1, 1)
    labels = labels.reshape(-1, 1)
    
    dL_dyhat = 2 * (pred - labels)  # (10000, 1)
    dsigmoid = pred * (1 - pred)  # (10000, 1)
    delta2 = dL_dyhat * dsigmoid  # (10000, 1)

    dL_dW2 = np.dot(delta2.T, a1) / len(X)  # (1, 3)
    dL_db2 = np.mean(delta2, axis=0)  # (1,)

    # Corrected dL_da1 calculation: delta2 is (10000, 1), W2 is (3,)
    # We want (10000, 3). We use np.outer or broadcasting.
    dL_da1 = delta2 * W2  # (10000, 1) * (3,) -> (10000, 3) via broadcasting
    delta1 = dL_da1 * (z1 > 0)  # (10000, 3)

    dL_dW1 = np.dot(delta1.T, X_norm) / len(X)  # (3, 2)
    dL_db1 = np.mean(delta1, axis=0)  # (3,)

    # Update weights
    W1 -= learning_rate * dL_dW1
    b1 -= learning_rate * dL_db1
    W2 -= learning_rate * dL_dW2.flatten()
    b2 -= learning_rate * dL_db2

    if (i + 1) % plot_every == 0 or i == 0:
        all_preds.append(pred.flatten().copy())
        epoch_list.append(i + 1)
        if (i + 1) % 10 == 0 or i == 0:
            print(f"Epoch {i+1}, Loss: {loss:.6f}")

print("Creating animation...")

# Setup Figure
fig = plt.figure(figsize=(14, 6))
ax1 = fig.add_subplot(121)
ax2 = fig.add_subplot(122, projection='3d')

# For 3D plotting, plotting 10,000 points every frame is slow.
# We'll use a subsample for visualization (e.g., a 20x20 grid)
subsample_idx = np.linspace(0, len(X)-1, 400, dtype=int)
X_sub = X[subsample_idx]
labels_sub = labels[subsample_idx].flatten()

def update(frame_idx):
    ax1.clear()
    ax2.clear()
    
    # Current epoch
    current_epoch = epoch_list[frame_idx]
    current_loss = losses[current_epoch-1]
    current_preds = all_preds[frame_idx][subsample_idx]
    
    # Plot Loss
    ax1.plot(range(1, current_epoch + 1), losses[:current_epoch], 'b-')
    ax1.set_title(f"Loss vs Epochs (Epoch {current_epoch})")
    ax1.set_xlabel("Epoch")
    ax1.set_ylabel("MSE Loss")
    ax1.set_xlim(0, epochs)
    ax1.set_ylim(0, max(losses) * 1.1)
    
    # Plot 3D Predictions vs True Labels
    ax2.scatter(X_sub[:, 0], X_sub[:, 1], labels_sub, color='green', label='True Labels', alpha=0.4)
    ax2.scatter(X_sub[:, 0], X_sub[:, 1], current_preds, color='red', marker='x', label='Predictions', alpha=0.8)
    ax2.set_title(f"3D Predictions at Epoch {current_epoch}")
    ax2.set_xlabel("X1")
    ax2.set_ylabel("X2")
    ax2.set_zlabel("Value")
    ax2.legend()
    
    plt.tight_layout()

# 10 epochs take 0.2 seconds -> 5 FPS (since we plot every epoch, it's 50 FPS for original speed)
# But "render every epoch and make it smoother" suggests we want higher resolution in time.
# If 10 epochs = 0.2s, then 1 epoch = 0.02s (50 FPS).
ani = FuncAnimation(fig, update, frames=len(epoch_list), interval=20)

# FFMPEG path if found
ffmpeg_path = r'C:\Users\pstay\code\PluginPlay\Marketing\Animation\node_modules\@remotion\compositor-win32-x64-msvc\ffmpeg.exe'
plt.rcParams['animation.ffmpeg_path'] = ffmpeg_path

try:
    # Attempting to save as MP4 using the found ffmpeg
    # We'll use a slightly different approach if the previous one failed
    # Actually, the error suggested 'rawvideo' format was not recognized, which is strange for ffmpeg.
    # It might be because this ffmpeg is too stripped down.
    
    # We will try to use the 'pillow' writer for GIF first (as it worked), 
    # then if it's there, we can try to convert the GIF to MP4 using ffmpeg command line directly.
    
    ani.save('training_animation.gif', writer='pillow', fps=50)
    print("Animation saved as training_animation.gif")
    
    # Now try to convert GIF to MP4 using ffmpeg directly via subprocess
    import subprocess
    cmd = [
        ffmpeg_path,
        '-i', 'training_animation.gif',
        '-movflags', 'faststart',
        '-pix_fmt', 'yuv420p',
        '-vf', 'scale=trunc(iw/2)*2:trunc(ih/2)*2',
        '-y',
        'training_animation.mp4'
    ]
    print("Converting GIF to MP4...")
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode == 0:
        print("Animation converted and saved as training_animation.mp4")
    else:
        print(f"Could not convert to MP4: {result.stderr}")

except Exception as e:
    print(f"Animation creation failed: {e}")

# plt.show() # Disabled for headless environment
